version: 2

updates:

- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 10
  reviewers:
  - robbevp